import { globSync } from 'glob'
import * as fs from 'fs'
import * as path from 'path'

const SOURCE_EXTENSION = '.test.ts'

const createNotice = ({ sourcePath }: { sourcePath: string }) =>
  `
// Do not edit! This file is autogenerated from 
// ${sourcePath} 
`.trim() + '\n\n'

globSync(`**/*${SOURCE_EXTENSION}`).forEach((sourcePath) => {
  const basename = path.basename(sourcePath)
  const destinationPath = path.resolve('./cjs/tests', basename)

  let content = fs.readFileSync(sourcePath, 'utf8')
  content = content.replace(/from '(.*).js'/gi, (_, p1) => `from '${p1}'`)
  content = `${createNotice({ sourcePath })}${content}`

  fs.writeFileSync(destinationPath, content, 'utf8')
})
